# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 08:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jointime', models.DateTimeField()),
                ('recordtime', models.DateTimeField()),
                ('couponrank', models.IntegerField()),
                ('status', models.CharField(choices=[('0', '\u5f85\u5ba1\u6838'), ('1', '\u6709\u6548'), ('2', '\u9000\u6b3e'), ('3', '\u5176\u4ed6')], max_length=20)),
                ('extra', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CouponVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponname', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=200)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('recordtime', models.DateTimeField(auto_now_add=True)),
                ('account', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('checkerlist', models.CharField(blank=True, max_length=200)),
                ('checkstatuslist', models.CharField(blank=True, max_length=200)),
                ('checktimelist', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('0', '\u5f85\u5ba1\u6838'), ('1', '\u6709\u6548'), ('2', '\u9000\u6b3e'), ('3', '\u5176\u4ed6')], max_length=20)),
                ('advice', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.TextField(max_length=200)),
                ('leaderid', models.IntegerField()),
                ('stage', models.CharField(choices=[('\u6821\u957f\u90e8', '\u6821\u957f\u90e8'), ('\u5e02\u573a\u90e8', '\u5e02\u573a\u90e8'), ('\u5ba2\u670d\u90e8', '\u5ba2\u670d\u90e8'), ('\u56fd\u5185\u90e8', '\u56fd\u5185\u90e8'), ('\u56fd\u5916\u90e8', '\u56fd\u5916\u90e8'), ('\u6ce1\u6ce1\u5c11\u513f\u90e8', '\u6ce1\u6ce1\u5c11\u513f\u90e8'), ('\u4f18\u80fd\u4e00\u5bf9\u4e00\u90e8', '\u4f18\u80fd\u4e00\u5bf9\u4e00\u90e8'), ('\u4f18\u80fd\u7cbe\u54c1\u73ed\u90e8', '\u4f18\u80fd\u7cbe\u54c1\u73ed\u90e8'), ('\u56fd\u9645\u6e38\u5b66\u90e8', '\u56fd\u9645\u6e38\u5b66\u90e8'), ('\u5c0f\u8bed\u79cd\u90e8', '\u5c0f\u8bed\u79cd\u90e8'), ('\u6559\u5b66\u90e8', '\u6559\u5b66\u90e8')], max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeindex', models.CharField(max_length=10, unique=True)),
                ('gradename', models.CharField(blank=True, max_length=200)),
                ('productname', models.CharField(blank=True, max_length=200)),
                ('gradeplace', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(default='\u533f\u540d', max_length=20)),
                ('extra', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lastlogin', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=1)),
                ('duty', models.CharField(choices=[('\u666e\u901a\u804c\u5458', '\u666e\u901a\u804c\u5458'), ('\u90e8\u95e8\u603b\u76d1', '\u90e8\u95e8\u603b\u76d1'), ('\u5e02\u573a\u603b\u76d1', '\u5e02\u573a\u603b\u76d1'), ('\u5ba2\u670d\u603b\u76d1', '\u5ba2\u670d\u603b\u76d1'), ('\u6821\u957f', '\u6821\u957f')], max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('\u7537', '\u7537'), ('\u5973', '\u5973')], max_length=10)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('leaderid', models.IntegerField()),
                ('extra', models.TextField(blank=True)),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.Department')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='couponverify',
            name='recorderid',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='coupon.UserList'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='couponid',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='coupon.CouponVerify'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='departmentid',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='coupon.Department'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='studentid',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='coupon.Student'),
        ),
    ]
