# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
