# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_grade_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
