# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_auto_20170704_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponverify',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '\u5f85\u5ba1\u6838'), ('1', '\u6709\u6548'), ('2', '\u9000\u6b3e'), ('3', '\u5176\u4ed6')], max_length=20),
        ),
    ]
