# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_auto_20170704_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponverify',
            name='account',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
