# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_auto_20170704_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='couponid',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='departmentid',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='studentid',
        ),
        migrations.AlterModelOptions(
            name='couponverify',
            options={'ordering': ['-id']},
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
