# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0008_auto_20170705_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounttype', models.CharField(default='\u4f18\u60e0\u5238', max_length=100)),
                ('discountnumber', models.CharField(max_length=100)),
                ('account', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('studentid', models.CharField(max_length=20)),
                ('registrationplace', models.CharField(max_length=100)),
                ('gradeid', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('extra', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
