# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-06 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0011_couponverify_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponverify',
            name='coreid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
