# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-06 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0012_couponverify_coreid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreid', models.CharField(blank=True, default='0', max_length=20)),
                ('ids', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
