# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0013_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='gradeid',
            new_name='gradeindex',
        ),
    ]
