# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0015_auto_20170711_0842'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together=set([('discountnumber', 'studentid')]),
        ),
    ]
