# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0016_auto_20170714_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponverify',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
