# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-19 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0017_auto_20170718_1132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together=set([('discountnumber', 'studentid', 'gradeindex')]),
        ),
    ]
