# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-19 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0018_auto_20170719_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponverify',
            name='couponname',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
