# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-20 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0019_auto_20170719_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['discountnumber']},
        ),
        migrations.AlterModelOptions(
            name='couponverify',
            options={'ordering': ['-recordtime']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-gradeindex']},
        ),
        migrations.AlterModelOptions(
            name='id',
            options={'ordering': ['-coreid']},
        ),
        migrations.AlterField(
            model_name='couponverify',
            name='status',
            field=models.CharField(choices=[('0', '\u5f85\u5ba1\u6838'), ('1', '\u6709\u6548')], default=0, max_length=20),
        ),
    ]
