# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-21 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0020_auto_20170720_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponverify',
            options={'ordering': ['-id']},
        ),
    ]
