# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0022_auto_20170721_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponverify',
            name='comment',
            field=models.CharField(default='\u65e0', max_length=200),
        ),
    ]
