# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0023_couponverify_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponverify',
            name='status',
            field=models.CharField(choices=[('0', '\u5f85\u5ba1\u6838'), ('1', '\u6709\u6548'), ('2', '\u5931\u8d25')], default=0, max_length=20),
        ),
    ]
